Create title component
Polymer-Japan/polymer-jp.org pull request #28
Opened 2017-12-08 10:04 UTC by usagi-f

https://github.com/Polymer-Japan/polymer-jp.org/issues/24

# Changelog

ページタイトル部分のコンポーネントを作りました。
関連するソースはそっちへ移動。

- `<a>` で囲う範囲を変更して、テキスト部分もリンクエリアに（issue対応）
- iron-flex-layoutがうまく適用できてなかったのを修正
- スクロール時に表示される青背景のタイトルは、統一性を持たせるためデザイン変更

# スクリーンショット

## 通常

![image](https://user-images.githubusercontent.com/9045135/33760165-20898112-dc48-11e7-9428-9000f323be15.png)
↑見た目上の変化はナシ

### リンク範囲
![image](https://user-images.githubusercontent.com/9045135/33760823-7c9dee00-dc4a-11e7-940c-7ebc64ec2726.png)

## 青背景（smallプロパティ付与時）

|NEW|OLD|
|---|---|
|![image](https://user-images.githubusercontent.com/9045135/33760196-35d657ca-dc48-11e7-8510-186f4918245a.png)|![image](https://user-images.githubusercontent.com/9045135/33760211-42e4fc6e-dc48-11e7-9fc3-d6e25c168714.png)|

2017-12-08 10:46 UTC, howking commented
ちょっとWIndows Chrome, Firefoxで微妙にアイコン位置が上にずれちゃうんですが、調整できますでしょうか？

![image](https://user-images.githubusercontent.com/13231263/33762545-339f5526-dc50-11e7-90b2-f3604ffbc1f0.png)
※ 左の新バージョンが若干上に寄ってる

2017-12-08 11:12 UTC, howking requested changes
いったんざっくり確認させていただきました。

2017-12-08 11:12 UTC, howking commented on src/polymer-jp-title.html
> +<link rel="import" href="../bower_components/paper-badge/paper-badge.html">
`iron-icon`のimportをpolymer-jp.htmlから移動してきてよい気がします。

2017-12-08 11:12 UTC, howking commented on src/polymer-jp-title.html
> +        display: flex;
ここらへんは下記のような指定でもいけたりしますか？

```css
@apply --layout-flex;
@apply --layout-center;
@apply --layout-center-justified;
```

- [参考: iron-flex-layout](https://www.webcomponents.org/element/PolymerElements/iron-flex-layout/page/GUIDE.md)
- [ソース: layout-center-justified](https://github.com/PolymerElements/iron-flex-layout/blob/f1d33ea9589e0a8d632ee4d5e00174df4c53661a/iron-flex-layout.html#L249)

2017-12-10 05:54 UTC, usagi-f commented on src/polymer-jp-title.html
> +        display: flex;
@howking 
https://github.com/Polymer-Japan/polymer-jp.org/pull/28/commits/4d398c4bc6d29af6e9034edcd92eb7a16b34f6d5

2017-12-10 05:54 UTC, usagi-f commented on src/polymer-jp-title.html
> +<link rel="import" href="../bower_components/paper-badge/paper-badge.html">
@howking 
https://github.com/Polymer-Japan/polymer-jp.org/pull/28/commits/77671db6b1c63a88caebcd0ce23973edb2aa244c

2017-12-10 10:11 UTC, usagi-f commented
https://github.com/Polymer-Japan/polymer-jp.org/pull/28/commits/3bee5f78293f01e4ae2a5b08a9ace6e84aaa372d
IE11用にCSSを一行足しました

↓修正後
![bandicam 2017-12-10 19-09-44-171](https://user-images.githubusercontent.com/9045135/33803907-d59e0276-dddd-11e7-859b-8ce23500e315.jpg)

2017-12-10 13:20 UTC, howking approved these changes

2017-12-10 13:24 UTC, merged